// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulpxkoavxtzrpbqqdcqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscHhrb2F2eHR6cnBicXFkY3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDIzMDMsImV4cCI6MjA2ODkxODMwM30.koheYEAgQWCNs5F5jlU_XhAZ6s3deb0gYnQFdBSKS2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});